export const questionPool = [
  { question: 'Who wrote "1984"?', options: ['George Orwell', 'Aldous Huxley', 'Ernest Hemingway', 'Mark Twain'], answer: 'George Orwell' },
  { question: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], answer: 'Canberra' },
  { question: 'What is the chemical symbol for water?', options: ['H2O', 'CO2', 'O2', 'NaCl'], answer: 'H2O' },
  { question: 'Who painted the Mona Lisa?', options: ['Leonardo da Vinci', 'Pablo Picasso', 'Vincent van Gogh', 'Claude Monet'], answer: 'Leonardo da Vinci' },
  { question: 'What planet is known as the Red Planet?', options: ['Mars', 'Jupiter', 'Saturn', 'Venus'], answer: 'Mars' },
  { question: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], answer: 'Pacific' },
  { question: 'Who discovered penicillin?', options: ['Alexander Fleming', 'Marie Curie', 'Isaac Newton', 'Albert Einstein'], answer: 'Alexander Fleming' },
  { question: 'In which year did the Titanic sink?', options: ['1912', '1905', '1898', '1923'], answer: '1912' },
  { question: 'What is the square root of 64?', options: ['6', '7', '8', '9'], answer: '8' },
  { question: 'Which country is known as the Land of the Rising Sun?', options: ['China', 'Japan', 'Thailand', 'Vietnam'], answer: 'Japan' },
  { question: 'What is the largest planet in our solar system?', options: ['Earth', 'Jupiter', 'Mars', 'Saturn'], answer: 'Jupiter' },
  { question: 'Who wrote "Pride and Prejudice"?', options: ['Jane Austen', 'Emily Bronte', 'Charles Dickens', 'Mark Twain'], answer: 'Jane Austen' },
  { question: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Chloroplast'], answer: 'Mitochondria' },
  { question: 'Which language is the most spoken worldwide?', options: ['Spanish', 'Mandarin', 'English', 'Hindi'], answer: 'Mandarin' },
  { question: 'Who was the first man to walk on the moon?', options: ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins'], answer: 'Neil Armstrong' },
  { question: 'What is the capital of France?', options: ['Rome', 'Madrid', 'Paris', 'Berlin'], answer: 'Paris' },
  { question: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Silver'], answer: 'Diamond' },
  { question: 'How many continents are there?', options: ['5', '6', '7', '8'], answer: '7' },
  { question: 'Who developed the theory of relativity?', options: ['Isaac Newton', 'Albert Einstein', 'Nikola Tesla', 'Galileo Galilei'], answer: 'Albert Einstein' },
  { question: 'Which element has the atomic number 1?', options: ['Oxygen', 'Helium', 'Hydrogen', 'Carbon'], answer: 'Hydrogen' },
  { question: 'What year did World War II end?', options: ['1945', '1939', '1950', '1963'], answer: '1945' },
  { question: 'Who is the author of "To Kill a Mockingbird"?', options: ['Harper Lee', 'J.K. Rowling', 'F. Scott Fitzgerald', 'George Orwell'], answer: 'Harper Lee' },
  { question: 'Which country gifted the Statue of Liberty to the USA?', options: ['England', 'France', 'Germany', 'Spain'], answer: 'France' },
  { question: 'What is the smallest prime number?', options: ['0', '1', '2', '3'], answer: '2' },
  { question: 'How many bones are in the human body?', options: ['206', '201', '198', '210'], answer: '206' },
  { question: 'Which is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], answer: 'Nile' },
  { question: 'What is the currency of Japan?', options: ['Yuan', 'Won', 'Yen', 'Dollar'], answer: 'Yen' },
  { question: 'Who painted "Starry Night"?', options: ['Vincent van Gogh', 'Claude Monet', 'Salvador Dalí', 'Pablo Picasso'], answer: 'Vincent van Gogh' },
  { question: 'Which gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'], answer: 'Carbon Dioxide' },
  { question: 'Who was the first President of the United States?', options: ['Abraham Lincoln', 'Thomas Jefferson', 'John Adams', 'George Washington'], answer: 'George Washington' },
  { question: 'What is the boiling point of water at sea level?', options: ['90°C', '100°C', '110°C', '120°C'], answer: '100°C' },
  { question: 'Who invented the telephone?', options: ['Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Guglielmo Marconi'], answer: 'Alexander Graham Bell' },
  { question: 'What is the largest mammal?', options: ['Elephant', 'Blue Whale', 'Giraffe', 'Shark'], answer: 'Blue Whale' },
  { question: 'Which planet is closest to the sun?', options: ['Earth', 'Venus', 'Mercury', 'Mars'], answer: 'Mercury' },
  { question: 'Who wrote "Hamlet"?', options: ['Charles Dickens', 'Mark Twain', 'William Shakespeare', 'Oscar Wilde'], answer: 'William Shakespeare' },
  { question: 'What is the capital of Italy?', options: ['Paris', 'Berlin', 'Rome', 'Athens'], answer: 'Rome' },
  { question: 'Which organ is responsible for pumping blood throughout the body?', options: ['Liver', 'Lung', 'Heart', 'Kidney'], answer: 'Heart' },
  { question: 'How many rings are there on the Olympic flag?', options: ['3', '4', '5', '6'], answer: '5' },
  { question: 'What is the primary ingredient in guacamole?', options: ['Tomato', 'Avocado', 'Cucumber', 'Pepper'], answer: 'Avocado' },
  { question: 'Who was the Greek god of the sea?', options: ['Zeus', 'Hades', 'Poseidon', 'Apollo'], answer: 'Poseidon' },
  { question: 'What is the capital of Egypt?', options: ['Cairo', 'Alexandria', 'Giza', 'Luxor'], answer: 'Cairo' },
  { question: 'Which planet is known for its rings?', options: ['Mars', 'Jupiter', 'Saturn', 'Neptune'], answer: 'Saturn' },
  { question: 'What does DNA stand for?', options: ['Deoxyribonucleic Acid', 'Dinucleic Acid', 'Dioxynitric Acid', 'Deoxynitrogen Acid'], answer: 'Deoxyribonucleic Acid' },
  { question: 'Who painted "The Persistence of Memory"?', options: ['Claude Monet', 'Pablo Picasso', 'Vincent van Gogh', 'Salvador Dalí'], answer: 'Salvador Dalí' },
  { question: 'What is the tallest mountain in the world?', options: ['K2', 'Mount Kilimanjaro', 'Mount Everest', 'Mount Fuji'], answer: 'Mount Everest' },
  { question: 'What is the main gas found in the air we breathe?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], answer: 'Nitrogen' },
  { question: 'Who wrote "The Odyssey"?', options: ['Homer', 'Virgil', 'Socrates', 'Plato'], answer: 'Homer' },
  { question: 'Which bird is known as the symbol of peace?', options: ['Eagle', 'Dove', 'Sparrow', 'Owl'], answer: 'Dove' },
  { question: 'What is the chemical symbol for gold?', options: ['Ag', 'Au', 'Pb', 'Fe'], answer: 'Au' },
  { question: 'Which country is famous for its pyramids?', options: ['Greece', 'Mexico', 'Egypt', 'India'], answer: 'Egypt' },
  { question: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], answer: '8' }
];